version: '3.8'

services:
  web:
    container_name: web
    image: ngthotuan/my-website
    restart: always
    volumes:
      - /appdata/user-upload:/app/user-upload
    ports:
      - 8080:3000
    networks:
      - my-website-network
    environment:
      DB_HOST: 'web_db'
      DB_PORT: '27017'
      DB_NAME: 'nguyenthotuan_me'
      DB_USER: 'admin'
      DB_PASSWORD: 'admin'

networks:
  my-website-network:
    name: my-website-network