services:

    mysql:
      image: mysql
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      command: --max_allowed_packet=32505856
      restart: always
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
  