# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - mongo-network
    ports:
      - 27017:27017
    volumes:
      - /appdata/db/mongo_nguyenthotuan.me:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin1
      MONGO_INITDB_ROOT_PASSWORD: admin1

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - mongo-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin0
      ME_CONFIG_BASICAUTH_PASSWORD: admin0
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin1
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1
      ME_CONFIG_OPTIONS_EDITORTHEME: rubyblue

networks:
  mongo-network: