
version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 8091:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainerdata:/data