version: '3'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    ports:
      - 27017:27017
    command: mongod --port 27017 --bind_ip_all --replSet rs0
  mongo2:
    container_name: mongo2
    image: mongo
    ports:
      - 27018:27017
    command: mongod --port 27017 --bind_ip_all --replSet rs0
  mongo3:
    container_name: mongo3
    image: mongo
    ports:
      - 27019:27017
    command: mongod --port 27017 --bind_ip_all --replSet rs0
